# Project: main
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Map.o Monster.o RpgCreature.o RpgPerson.o SwordMan.o Thief.o Magicion.o
LINKOBJ  = main.o Map.o Monster.o RpgCreature.o RpgPerson.o SwordMan.o Thief.o Magicion.o
LIBS     = -L"C:/Users/USER/Desktop/Jacky/DevCppPortable/MinGW64/lib" -L"C:/Users/USER/Desktop/Jacky/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/USER/Desktop/Jacky/DevCppPortable/MinGW64/include" -I"C:/Users/USER/Desktop/Jacky/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/USER/Desktop/Jacky/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/USER/Desktop/Jacky/DevCppPortable/MinGW64/include" -I"C:/Users/USER/Desktop/Jacky/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/USER/Desktop/Jacky/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/USER/Desktop/Jacky/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = project.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Map.o: Map.cpp
	$(CPP) -c Map.cpp -o Map.o $(CXXFLAGS)

Monster.o: Monster.cpp
	$(CPP) -c Monster.cpp -o Monster.o $(CXXFLAGS)

RpgCreature.o: RpgCreature.cpp
	$(CPP) -c RpgCreature.cpp -o RpgCreature.o $(CXXFLAGS)

RpgPerson.o: RpgPerson.cpp
	$(CPP) -c RpgPerson.cpp -o RpgPerson.o $(CXXFLAGS)

SwordMan.o: SwordMan.cpp
	$(CPP) -c SwordMan.cpp -o SwordMan.o $(CXXFLAGS)

Thief.o: Thief.cpp
	$(CPP) -c Thief.cpp -o Thief.o $(CXXFLAGS)

Magicion.o: Magicion.cpp
	$(CPP) -c Magicion.cpp -o Magicion.o $(CXXFLAGS)
